version: "3.9"

services:
  # ==========================
  # ðŸ”¹ MySQL
  # ==========================
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_tingeso
      MYSQL_USER: diego
      MYSQL_PASSWORD: diego1234
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-mysql:/docker-entrypoint-initdb.d
    networks:
      - tingeso-net
    ports:
      - "3307:3306"

  # ==========================
  # ðŸ”¹ Backend cluster (3 instancias)
  # ==========================
  backend1:
    image: diegoraar/backend-tingeso:latest
    #build: ./backend_tingeso
    container_name: backend1
    restart: always
    environment:
      - DB_HOST=mysql
      - DB_NAME=db_tingeso
      - DB_USER=diego
      - DB_PASSWORD=diego1234
    depends_on:
      - mysql
    networks:
      - tingeso-net
    expose:
      - "8090"

  backend2:
    image: diegoraar/backend-tingeso:latest
    #build: ./backend_tingeso
    container_name: backend2
    restart: always
    environment:
      - DB_HOST=mysql
      - DB_NAME=db_tingeso
      - DB_USER=diego
      - DB_PASSWORD=diego1234
    depends_on:
      - mysql
    networks:
      - tingeso-net
    expose:
      - "8090"

  backend3:
    image: diegoraar/backend-tingeso:latest
    #build: ./backend_tingeso
    container_name: backend3
    restart: always
    environment:
      - DB_HOST=mysql
      - DB_NAME=db_tingeso
      - DB_USER=diego
      - DB_PASSWORD=diego1234
    depends_on:
      - mysql
    networks:
      - tingeso-net
    expose:
      - "8090"

  # ==========================
  # ðŸ”¹ Nginx Load Balancer
  # ==========================
  nginx-loadbalancer:
    image: nginx:latest
    container_name: nginx-loadbalancer
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "70:80"   
    depends_on:
      - backend1
      - backend2
      - backend3
      - frontend
    networks:
      - tingeso-net
    restart: always

  # ==========================
  # ðŸ”¹ Keycloak
  # ==========================
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    command: start-dev --import-realm --http-relative-path=/auth --hostname=54.94.174.49 --hostname-strict=false --hostname-backchannel-dynamic=true
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak_db
      - KC_DB_USERNAME=diego
      - KC_DB_PASSWORD=diego1234
      - KC_DB_SCHEMA=keycloak_db
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_PROXY_HEADERS=xforwarded
      - KEYCLOAK_FRONTEND_URL=http://54.94.174.49:70/auth
      - KC_HOSTNAME=54.94.174.49
      - KC_HOSTNAME_PORT=70
    volumes:
      - ./keycloak-config/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - tingeso-net
    restart: always

  # ==========================
  # ðŸ”¹ Frontend (React)
  # ==========================
  frontend:
    image: diegoraar/frontend-tingeso:latest
    #build: ./frontend-tingeso
    container_name: frontend
    restart: always
    depends_on:
      - keycloak
    expose:
      - "80"
    networks:
      - tingeso-net
    volumes:                                                                   
      - ./frontend-tingeso/nginx.conf:/etc/nginx/conf.d/default.conf:ro 

# ==========================
# ðŸ”¸ Volumes 
# ==========================
volumes:
  mysql_data:

# ==========================
# ðŸ”¸ Network
# ==========================
networks:
  tingeso-net:
    driver: bridge
